### ISSUE TITLE
Update the experience section

### ISSUE THREAD

**Issue by anjula-sack** [anjula-sack/my-portofolio#10]
- Use the descriptions from the https://www.linkedin.com/in/anjula-sack/ LinkedIn profile
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/43912578/218016007-80e2f972-9c94-4847-a9cf-2be6f43c8c8a.png">

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
@anjula-sack Should I input all the details in the experience section in linkedin

![image](https://user-images.githubusercontent.com/97069900/218233127-77363eb5-0cda-4106-86e9-0bcf66c27859.png)

**Comment by Sanjana0319** [comment]
I would like to work on this.

**Comment by anjula-sack** [comment]
@YoshithaRathnayake I assigned @Sanjana0319 since this is urgent.
