### ISSUE TITLE
Update the footer

### ISSUE THREAD

**Issue by anjula-sack** [anjula-sack/my-portofolio#19]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/43912578/225197241-8ec02822-0262-4c13-8202-94bf495d0a1a.png">

1. Add the social media links to the footer
2. Remove the USEFUL LINKS section
3. Remove the subtitle
<img width="130" alt="Screenshot 2023-03-15 at 8 52 42 AM" src="https://user-images.githubusercontent.com/43912578/225197923-38131a1d-427d-4312-bf9a-400f600fff47.png">

**Comment by Sanjana0319** [comment]
I would like to work on this.
