### ISSUE TITLE
Break the simulations card content from the URLs

### ISSUE THREAD

**Issue by YoshithaRathnayake** [anjula-sack/my-portofolio#2]
- Currently, all the content in the simulations cards are in one line
- Divide them from the URLs

![image](https://user-images.githubusercontent.com/97069900/216689562-b878e0b3-353d-4bf9-9d4f-7f3b56ee932b.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this? @anjula-sack

**Comment by anjula-sack** [comment]
> Shall I work on this? @anjula-sack

Go ahead! @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this? @anjula-sack
> 
> Go ahead! @YoshithaRathnayake

Thank you @anjula-sack
