### ISSUE TITLE
Link the URLs in the simulations cards

### ISSUE THREAD

**Issue by YoshithaRathnayake** [anjula-sack/my-portofolio#3]
- Currently, the links in the simulation cards are not linked
- Link them according to the URL

![image](https://user-images.githubusercontent.com/97069900/216689306-818b82cb-67d5-4c3a-a7c1-5e2e2d5d8a21.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this? @anjula-sack

**Comment by anjula-sack** [comment]
> Shall I work on this? @anjula-sack

Go ahead! @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this? @anjula-sack
> 
> Go ahead! @YoshithaRathnayake

Thank you @anjula-sack
